#!/bin/bash
set -e

# Set default values from environment variables
RPCUSER=${RPCUSER:-umbrel}
RPCPASSWORD=${RPCPASSWORD:-changeme}
RPCALLOWIP=${RPCALLOWIP:-0.0.0.0/0}
MAXCONNECTIONS=${MAXCONNECTIONS:-300}
TESTNET=${TESTNET:-0}
DAEMON=${DAEMON:-1}
SERVER=${SERVER:-1}
TXINDEX=${TXINDEX:-1}
DISABLEWALLET=${DISABLEWALLET:-0}
LISTEN=${LISTEN:-1}
DISCOVER=${DISCOVER:-1}
UPNP=${UPNP:-0}

# Create digibyte.conf
DIGIBYTE_CONF="/root/.digibyte/digibyte.conf"

echo "Generating DigiByte configuration..."
mkdir -p /root/.digibyte

cat > "$DIGIBYTE_CONF" << EOF
# DigiByte Configuration - Generated by Umbrel App
daemon=${DAEMON}
server=${SERVER}
listen=${LISTEN}
discover=${DISCOVER}
upnp=${UPNP}

# Network settings
maxconnections=${MAXCONNECTIONS}
testnet=${TESTNET}

# RPC settings  
rpcuser=${RPCUSER}
rpcpassword=${RPCPASSWORD}
rpcallowip=${RPCALLOWIP}
rpcbind=0.0.0.0
rpcport=14022

# Wallet settings
disablewallet=${DISABLEWALLET}

# Transaction indexing
txindex=${TXINDEX}

# Logging
logtimestamps=1
logips=1
shrinkdebugfile=1

# Performance optimizations for Umbrel
dbcache=512
maxorphantx=100
maxmempool=300
mempoolexpiry=72

# Network specific ports
EOF

if [ "$TESTNET" = "1" ]; then
    echo "port=12026" >> "$DIGIBYTE_CONF"
    echo "rpcport=14023" >> "$DIGIBYTE_CONF"
else
    echo "port=12024" >> "$DIGIBYTE_CONF"
fi

echo "Configuration written to $DIGIBYTE_CONF"

# Set proper ownership
chown -R digibyte:digibyte /root/.digibyte

# Graceful shutdown handler
shutdown_handler() {
    echo "Received shutdown signal, stopping DigiByte gracefully..."
    if pgrep digibyted > /dev/null; then
        digibyte-cli stop 2>/dev/null || true
        
        # Wait for process to exit gracefully
        local count=0
        while pgrep digibyted > /dev/null && [ $count -lt 30 ]; do
            sleep 1
            count=$((count + 1))
        done
        
        # Force kill if still running
        if pgrep digibyted > /dev/null; then
            echo "Force stopping DigiByte process..."
            pkill -9 digibyted
        fi
    fi
    exit 0
}

# Setup signal handlers
trap shutdown_handler SIGTERM SIGINT

# Display startup information
echo "========================================"
echo "DigiByte Node Starting"
echo "========================================"
echo "Network: $([ "$TESTNET" = "1" ] && echo "Testnet" || echo "Mainnet")"
echo "RPC User: $RPCUSER"
echo "Max Connections: $MAXCONNECTIONS"
echo "Transaction Index: $([ "$TXINDEX" = "1" ] && echo "Enabled" || echo "Disabled")"
echo "Wallet: $([ "$DISABLEWALLET" = "1" ] && echo "Disabled" || echo "Enabled")"
echo "========================================"

# Start DigiByte daemon
if [ "$1" = "digibyted" ]; then
    exec digibyted -conf="$DIGIBYTE_CONF" -datadir=/root/.digibyte -printtoconsole
else
    exec "$@"
fi