services:
  # Umbrel's app proxy - required for all apps
  app_proxy:
    environment:
      APP_HOST: vpn
      APP_PORT: 8090

  # VPN container - all traffic routes through here
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: qbittorrent-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # Expose qBittorrent web UI port
      - 8090:8090
      # Expose qBittorrent connection port
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ${APP_DATA_DIR}/gluetun:/gluetun
    environment:
      # VPN Configuration from user form
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE:-openvpn}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=${SERVER_CITIES}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      
      # Security and networking
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
      - FIREWALL_VPN_INPUT_PORTS=6881
      
      # Health check and logging
      - HEALTH_SERVER_ADDRESS=:9999
      - LOG_LEVEL=info
      
      # User permissions
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # qBittorrent container - routes through VPN
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-app
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8090
    restart: unless-stopped
