# docker-compose.yml
# This file defines the services that make up the app.
# This is the full version including the VPN service.
services:
  # Umbrel's app proxy service - REQUIRED
  app_proxy:
    environment:
      APP_HOST: vpn
      APP_PORT: 8081

  # The VPN container. All network traffic will go through here.
  vpn:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
    volumes:
      # Mapped to the app's specific data directory.
      - ${APP_DATA_DIR}/gluetun:/gluetun
    environment:
      - VPN_ENABLED=true #
      - VPN_CONF=wg0 #
      - VPN_PROVIDER=pia #
      - VPN_LAN_NETWORK=192.168.1.0/24 #
      - VPN_LAN_LEAK_ENABLED=false #
      - VPN_EXPOSE_PORTS_ON_LAN #
      - VPN_AUTO_PORT_FORWARD=true #
      - VPN_AUTO_PORT_FORWARD_TO_PORTS= #
      - VPN_FIREWALL_TYPE=auto #
      - VPN_HEALTHCHECK_ENABLED=false #
      - VPN_NAMESERVERS= #
      - VPN_PIA_USER #
      - VPN_PIA_PASS #
      - VPN_PIA_PREFERRED_REGION #
      - VPN_PIA_DIP_TOKEN=no #
      - VPN_PIA_PORT_FORWARD_PERSIST=false #
      - PRIVOXY_ENABLED=false #
      - UNBOUND_ENABLED=false #
      - UNBOUND_NAMESERVERS #

    restart: unless-stopped

  # The qBittorrent container.
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:vpn"
    depends_on:
      - vpn
    volumes:
      # Mapped to the app's specific data directory.
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/downloads:/data
    environment:
      - PUID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
      - LIBTORRENT=v1
    restart: unless-stopped
