# docker-compose.yml
# VERSION 7: Corrected invisible characters causing YAML parsing errors.

services:
  # Umbrel's app proxy service - REQUIRED
  app_proxy:
    image: getumbrel/app-proxy:v1.1.0
    environment:
      APP_HOST: qbittorrent
      APP_PORT: 8080
    restart: unless-stopped

  # The VPN container
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: qbittorrent-vpn-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - ${APP_DATA_DIR}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${OPENVPN_PROTOCOL}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=${SERVER_CITIES}
      - PUID=1000
      - PGID=1000
      - VPN_LAN_NETWORK=192.168.0.0/16
      - VPN_PORT_FORWARDING=on
      - HTTP_CONTROL_SERVER_PORT=disabled
      - DNS_ADDRESS=off
    restart: unless-stopped

  # The qBittorrent container
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-app
    network_mode: "service:vpn"
    depends_on:
      - vpn
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/downloads:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    restart: unless-stopped
