# docker-compose.yml
# This file defines the services that make up the app.
# This is the full version including the VPN service.
services:
  # Umbrel's app proxy service - REQUIRED
  app_proxy:
    environment:
      APP_HOST: vpn
      APP_PORT: 8080

  # The VPN container. All network traffic will go through here.
  vpn:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
    volumes:
      # Mapped to the app's specific data directory.
      - ${APP_DATA_DIR}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_PROTOCOL=${OPENVPN_PROTOCOL}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=${SERVER_CITIES}
      - PUID=1000
      - PGID=1000
      - VPN_LAN_NETWORK=192.168.0.0/16
    restart: unless-stopped

  # The qBittorrent container.
  qbittorrent:
    image: linuxserver/qbittorrent
    network_mode: "service:vpn"
    depends_on:
      - vpn
    volumes:
      # Mapped to the app's specific data directory.
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/downloads:/data
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    restart: unless-stopped
