version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: vpn
      APP_PORT: 8080

  vpn:
    image: qmcgaw/gluetun:latest
    container_name: qbittorrent-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ${APP_DATA_DIR}/gluetun:/gluetun
    environment:
      # VPN Configuration - Set these in Umbrel environment or via file
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-privateinternetaccess}
      - VPN_TYPE=${VPN_TYPE:-openvpn}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Switzerland}
      - SERVER_CITIES=${SERVER_CITIES}
      
      # Security settings
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
      - FIREWALL_VPN_INPUT_PORTS=6881
      
      # Health check and monitoring
      - HEALTH_SERVER_ADDRESS=:9999
      - LOG_LEVEL=info
      
      # User permissions
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9999 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-app
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    restart: unless-stopped
