services:
  digibyte:
    image: blocknetdx/digibyte:v8.22.0-rc3-staging
    restart: on-failure
    stop_grace_period: 1m
    
    # Internal networking only
    expose:
      - "12024"     # P2P port
      - "14022"     # RPC port
    
    environment:
      # RPC Configuration
      - RPCUSER=umbrel
      - RPCPASSWORD=${APP_PASSWORD}
      - RPCALLOWIP=0.0.0.0/0
      
      # Network Configuration
      - MAXCONNECTIONS=300
      - TESTNET=0
      
      # Node Configuration optimized for Umbrel
      - DAEMON=1
      - SERVER=1
      - TXINDEX=1
      - DISABLEWALLET=0
      - LISTEN=1
      - DISCOVER=1
      - UPNP=0
      
      # Data directories
      - DATADIR=/data/blockchain
      - CONFIGDIR=/data/config
    
    volumes:
      - ${APP_DATA_DIR}/config:/data/config
      - ${APP_DATA_DIR}/blockchain:/data/blockchain
      - ${APP_DATA_DIR}/logs:/data/logs

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - digibyte
    
    environment:
      - DIGIBYTE_RPC_HOST=digibyte
      - DIGIBYTE_RPC_PORT=14022
      - DIGIBYTE_RPC_USER=umbrel
      - DIGIBYTE_RPC_PASSWORD=${APP_PASSWORD}
      - NODE_ENV=production
    
    volumes:
      - ${APP_DATA_DIR}/web:/app/data
    
    ports:
      - "${APP_PORT}:3001"