services:
  digibyte:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    
    environment:
      - RPCUSER=umbrel
      - RPCPASSWORD=${APP_PASSWORD}
      - RPCALLOWIP=0.0.0.0/0
      - MAXCONNECTIONS=300
      - TESTNET=0
      - DAEMON=1
      - SERVER=1
      - TXINDEX=1
      - DISABLEWALLET=0
      - LISTEN=1
      - DISCOVER=1
      - UPNP=0
    
    volumes:
      - ${APP_DATA_DIR}/data:/root/.digibyte
      - ${APP_DATA_DIR}/logs:/var/log/digibyte
    
    ports:
      - "12024:12024"
      - "14022:14022"
    
    networks:
      default:
        ipv4_address: $APP_DISERIC_DIGIBYTE_NODE_DIGIBYTE_IP

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - digibyte
    
    environment:
      - DIGIBYTE_RPC_HOST=digibyte
      - DIGIBYTE_RPC_PORT=14022
      - DIGIBYTE_RPC_USER=umbrel
      - DIGIBYTE_RPC_PASSWORD=${APP_PASSWORD}
      - NODE_ENV=production
    
    volumes:
      - ${APP_DATA_DIR}/web:/app/data
    
    ports:
      - "${APP_PORT}:3001"
    
    networks:
      default:
        ipv4_address: $APP_DISERIC_DIGIBYTE_NODE_WEB_IP