services:
  main:
    image: nginx:alpine
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/usr/share/nginx/html
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - APP_HOST=main
      - APP_PORT=80