#!/bin/bash
set -e

# Set default values
RPCUSER=${RPCUSER:-umbrel}
RPCPASSWORD=${RPCPASSWORD:-changeme}
RPCALLOWIP=${RPCALLOWIP:-0.0.0.0/0}
MAXCONNECTIONS=${MAXCONNECTIONS:-300}
TESTNET=${TESTNET:-0}
DAEMON=${DAEMON:-1}
SERVER=${SERVER:-1}
TXINDEX=${TXINDEX:-1}
DISABLEWALLET=${DISABLEWALLET:-0}
LISTEN=${LISTEN:-1}
DISCOVER=${DISCOVER:-1}
UPNP=${UPNP:-0}

# Create digibyte.conf if it doesn't exist
DIGIBYTE_CONF="/root/.digibyte/digibyte.conf"

if [ ! -f "$DIGIBYTE_CONF" ]; then
    echo "Creating DigiByte configuration file..."
    mkdir -p /root/.digibyte
    
    cat > "$DIGIBYTE_CONF" << EOC
# DigiByte Configuration File
# Generated by Umbrel DigiByte App

# Basic settings
daemon=${DAEMON}
server=${SERVER}
listen=${LISTEN}
discover=${DISCOVER}
upnp=${UPNP}

# Network settings
maxconnections=${MAXCONNECTIONS}
testnet=${TESTNET}

# RPC settings
rpcuser=${RPCUSER}
rpcpassword=${RPCPASSWORD}
rpcallowip=${RPCALLOWIP}
rpcport=14022

# Wallet settings
disablewallet=${DISABLEWALLET}

# Transaction index
txindex=${TXINDEX}

# Logging
logtimestamps=1
logips=1

# Performance settings
dbcache=512
maxorphantx=100
maxmempool=300

# Network specific settings
EOC

    if [ "$TESTNET" = "1" ]; then
        echo "rpcport=14023" >> "$DIGIBYTE_CONF"
        echo "port=12026" >> "$DIGIBYTE_CONF"
    else
        echo "port=12024" >> "$DIGIBYTE_CONF"
    fi
    
    echo "Configuration file created at $DIGIBYTE_CONF"
fi

# Set proper permissions
chown -R digibyte:digibyte /root/.digibyte 2>/dev/null || true

# Function to handle shutdown
shutdown_handler() {
    echo "Shutting down DigiByte node gracefully..."
    if pidof digibyted > /dev/null; then
        digibyte-cli stop 2>/dev/null || true
        # Wait for process to stop
        while pidof digibyted > /dev/null; do
            sleep 1
        done
    fi
    exit 0
}

# Trap shutdown signals
trap shutdown_handler SIGTERM SIGINT

# Start DigiByte daemon
echo "Starting DigiByte node..."
echo "Network: $([ "$TESTNET" = "1" ] && echo "testnet" || echo "mainnet")"
echo "RPC User: $RPCUSER"
echo "Max Connections: $MAXCONNECTIONS"
echo "Transaction Index: $([ "$TXINDEX" = "1" ] && echo "enabled" || echo "disabled")"
echo "Wallet: $([ "$DISABLEWALLET" = "1" ] && echo "disabled" || echo "enabled")"

if [ "$1" = "digibyted" ]; then
    # Start digibyted with proper configuration
    exec digibyted -conf="$DIGIBYTE_CONF" -datadir=/root/.digibyte -printtoconsole
else
    # Run custom command
    exec "$@"
fi